[project]
name = "webtestpilot-sjtu-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest-webtestpilot>=0.1.0",
    "webtestpilot==0.1.4",
]
